name: Deploy Azure Data Factory
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  terraform:
    name: Deploy ADF
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [dev, prod]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: "00c0869d-66c1-4ae0-911b-acdead400998"
          tenant-id: "cb561bac-8eae-4e86-979a-765c514af3ae"
          subscription-id: "59b8512d-88be-476b-bfd3-8118c43006bb"
