name: Deploy Azure Data Factory

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Deploy ADF
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: "e14a7964-a03f-4ce2-b8bc-dd7f5df9527d"
          tenant-id: "cb561bac-8eae-4e86-979a-765c514af3ae"
          subscription-id: "59b8512d-88be-476b-bfd3-8118c43006bb"

      - name: Terraform Init
        run: |
          cd azure-infra
          terraform init

      - name: Terraform Plan
        run: |
          cd azure-infra
          terraform plan -out=tfplan \
            -var "resource_group_name=hardcoded-resource-group" \
            -var "location=East US" \
            -var "adf_name=hardcoded-adf"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          cd azure-infra
          terraform apply -auto-approve tfplan
