name: Deploy Azure Data Factory
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  terraform:
    name: Deploy ADF
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [dev, prod]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: |
          cd azure-infra/environments/${{ matrix.environment }}
          terraform init

      - name: Terraform Plan
        run: |
          cd azure-infra/environments/${{ matrix.environment }}
          terraform plan -out=tfplan -var "resource_group_name=${{ secrets.RESOURCE_GROUP_${{ matrix.environment }}}}" -var "location=${{ secrets.LOCATION_${{ matrix.environment }}}}" -var "adf_name=${{ secrets.ADF_NAME_${{ matrix.environment }}}}"

      - name: Terraform Apply (only on main/release)
        if: github.ref == 'refs/heads/main' || github.event_name == 'release'
        run: |
          cd azure-infra/environments/${{ matrix.environment }}
          terraform apply -auto-approve tfplan
